---
# Add 'noetic' label if any files in noetic/ folder are changed by a PR
noetic:
- noetic/*

# Add 'humble' label if any files in humble/ folder are changed by a PR
humble:
- humble/*

# Add 'jazzy' label if any files in jazzy/ folder are changed by a PR
jazzy:
- jazzy/*

# Add 'kilted' label if any files in kilted/ folder are changed by a PR
kilted:
- kilted/*

# Add 'rolling' label if any files in rolling/ folder are changed by a PR
rolling:
- rolling/*

# Add 'rosdep' label if any files in rosdep/ folder are changed by a PR
rosdep:
- rosdep/*

# Add 'end-of-life' label if any files are in folders for versions that are no longer supported
end-of-life:
# ROS 1
- groovy/*
- hydro/*
- indigo/*
- jade/*
- kinetic/*
- lunar/*
- melodic/*
- noetic/*
# ROS 2
- ardent/*
- bouncy/*
- crystal/*
- dashing/*
- eloquent/*
- foxy/*
- galactic/*
- iron/*
