---
name: "Pull Request Labeler"
# this is fine since gha runs with yaml 1.2
on:  # yamllint disable-line rule:truthy
- pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/labeler@v5  # 8558fd74291d67161a8a78ce36a881fa63b766a9
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/labeler-config.yaml"
